server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE
          predicates:
            - Path=/ead-authuser/**
        - id: courses-service
          uri: lb://EAD-COURSE-SERVICE
          predicates:
            - Path=/ead-course/**
        - id: notifications-service
          uri: lb://EAD-NOTIFICATION-SERVICE
          predicates:
              - Path=/ead-notification/**

ead:
  service-registry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    prefer-ip-address: true
    hostname: localhost