spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-courses
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    jdbc:
      lob.non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

server:
  port: 8082

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    prefer-ip-address: true
    hostname: localhost