spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-courses
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    jdbc:
      lob.non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

server:
  port: 8082
