server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/matheusvidal21/ead-config-server-repo
          default-label: main
          username: matheusvidal21
          password: ${GITHUB_TOKEN}

ead:
  config-server:
    username: configserver
    password: 'ead123cs'
  service-registry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    prefer-ip-address: true
    hostname: localhost